// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/premium/Hero.tsx": () => import("../components/mockups/premium/Hero.tsx"),
  "./components/mockups/premium/ToolCard.tsx": () => import("../components/mockups/premium/ToolCard.tsx")
};
