import { db } from "./index";
import {
  categoriesTable, toolsTable, blogPostsTable, newsTable,
  tagsTable, newsletterSubscribersTable
} from "./schema";

async function seed() {
  console.log("Seeding database...");

  // Categories
  const categories = await db.insert(categoriesTable).values([
    { name: "AI Writing", slug: "ai-writing", description: "Writing assistants, copywriting, content generation", icon: "PenLine", sortOrder: 1 },
    { name: "Image Generation", slug: "image-generation", description: "AI image and art creation tools", icon: "Image", sortOrder: 2 },
    { name: "Video & Animation", slug: "video-animation", description: "AI video creation and animation tools", icon: "Video", sortOrder: 3 },
    { name: "Code & Development", slug: "code-development", description: "AI coding assistants and development tools", icon: "Code2", sortOrder: 4 },
    { name: "Chatbots & Assistants", slug: "chatbots-assistants", description: "Conversational AI and virtual assistants", icon: "MessageSquare", sortOrder: 5 },
    { name: "Audio & Music", slug: "audio-music", description: "AI audio generation, voice, and music tools", icon: "Music", sortOrder: 6 },
    { name: "Productivity", slug: "productivity", description: "AI tools to boost productivity and automate tasks", icon: "Zap", sortOrder: 7 },
    { name: "Research & Analysis", slug: "research-analysis", description: "AI tools for research, data analysis, and insights", icon: "BarChart2", sortOrder: 8 },
    { name: "SEO & Marketing", slug: "seo-marketing", description: "AI tools for SEO, marketing, and growth", icon: "TrendingUp", sortOrder: 9 },
    { name: "Design & UI", slug: "design-ui", description: "AI tools for design, UI/UX, and visual creation", icon: "Palette", sortOrder: 10 },
    { name: "Education & Learning", slug: "education-learning", description: "AI tools for learning, tutoring, and education", icon: "GraduationCap", sortOrder: 11 },
    { name: "Business & Finance", slug: "business-finance", description: "AI tools for business intelligence and finance", icon: "Briefcase", sortOrder: 12 },
  ]).returning().onConflictDoNothing();

  console.log(`Inserted ${categories.length} categories`);

  const catMap = new Map(categories.map((c) => [c.slug, c.id]));

  // Tools
  const tools = await db.insert(toolsTable).values([
    {
      name: "ChatGPT",
      slug: "chatgpt",
      websiteUrl: "https://chat.openai.com",
      shortDescription: "OpenAI's flagship conversational AI that can assist with writing, analysis, coding, and virtually any text-based task.",
      longDescription: "ChatGPT is a large language model developed by OpenAI that has become the world's most popular AI assistant. Built on the GPT-4 architecture, it can engage in nuanced conversations, help with complex reasoning, generate creative content, assist with coding, analyze data, and much more. With support for voice, vision, and custom GPTs, it's the most versatile AI tool available today.",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/240px-ChatGPT_logo.svg.png",
      categoryId: catMap.get("chatbots-assistants"),
      pricing: "freemium",
      status: "featured",
      isVerified: true,
      isEditorChoice: true,
      views: 45230,
      clicks: 12400,
      bookmarkCount: 3240,
      ratingAvg: 4.7,
      reviewCount: 1820,
      trendingScore: 98.5,
      ownerName: "OpenAI",
      websiteUrl: "https://chat.openai.com",
      githubUrl: "https://github.com/openai",
      launchDate: "2022-11-30",
      aiModel: "GPT-4o",
      features: ["Conversational AI", "Code generation", "Image analysis", "Voice mode", "Custom GPTs", "Plugin ecosystem", "File analysis"],
      pros: ["Extremely versatile", "Best-in-class reasoning", "Huge ecosystem", "Regular updates"],
      cons: ["Can hallucinate facts", "Free tier limited", "No real-time internet in base model"],
      platforms: ["Web", "iOS", "Android", "API"],
      integrations: ["Zapier", "Make", "Slack", "Microsoft 365"],
      tags: ["chatbot", "writing", "coding", "analysis", "GPT-4"],
    },
    {
      name: "Claude",
      slug: "claude",
      websiteUrl: "https://claude.ai",
      shortDescription: "Anthropic's AI assistant known for its thoughtful, nuanced responses and strong reasoning capabilities.",
      longDescription: "Claude is an AI assistant by Anthropic, designed with safety and helpfulness at its core. Claude excels at long-context tasks, nuanced analysis, creative writing, and coding. It can handle documents up to 200K tokens, making it ideal for research, legal review, and large codebase analysis. Claude is known for its honest, balanced responses and reluctance to produce harmful content.",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Claude_AI_logo.svg/240px-Claude_AI_logo.svg.png",
      categoryId: catMap.get("chatbots-assistants"),
      pricing: "freemium",
      status: "featured",
      isVerified: true,
      isEditorChoice: true,
      views: 32100,
      clicks: 9800,
      bookmarkCount: 2100,
      ratingAvg: 4.8,
      reviewCount: 987,
      trendingScore: 95.2,
      ownerName: "Anthropic",
      launchDate: "2023-03-14",
      aiModel: "Claude 3.5 Sonnet",
      features: ["200K context window", "Document analysis", "Code generation", "Reasoning", "Safety-focused", "Artifacts feature"],
      pros: ["Exceptional reasoning", "Long context handling", "Nuanced writing", "Safety-first design"],
      cons: ["No image generation", "API can be expensive", "Slower than some competitors"],
      platforms: ["Web", "iOS", "Android", "API"],
      integrations: ["Slack", "Cursor", "GitHub"],
      tags: ["chatbot", "reasoning", "long-context", "writing", "analysis"],
    },
    {
      name: "Midjourney",
      slug: "midjourney",
      websiteUrl: "https://midjourney.com",
      shortDescription: "The world's leading AI image generation tool, known for stunning artistic quality and photorealistic outputs.",
      longDescription: "Midjourney is an independent research lab and AI art generator that has set the standard for AI image quality. Accessed primarily through Discord, Midjourney creates breathtaking images from text prompts with an aesthetic that has redefined what AI art looks like. Version 6.1 brings even more photorealism, detail, and artistic control, making it the go-to tool for designers, artists, and creative directors.",
      categoryId: catMap.get("image-generation"),
      pricing: "paid",
      status: "featured",
      isVerified: true,
      isEditorChoice: true,
      views: 38700,
      clicks: 11200,
      bookmarkCount: 4100,
      ratingAvg: 4.8,
      reviewCount: 2340,
      trendingScore: 96.0,
      ownerName: "Midjourney Inc.",
      launchDate: "2022-07-12",
      features: ["Photorealistic generation", "Artistic styles", "Image variations", "Upscaling", "Pan/Zoom", "Style reference", "Character reference"],
      pros: ["Unmatched image quality", "Massive style range", "Active community", "Regular improvements"],
      cons: ["Discord-only interface", "No free tier", "Limited commercial usage on basic plan"],
      platforms: ["Discord", "Web (Beta)"],
      integrations: ["Discord"],
      tags: ["image generation", "art", "design", "creative", "photorealistic"],
    },
    {
      name: "GitHub Copilot",
      slug: "github-copilot",
      websiteUrl: "https://github.com/features/copilot",
      shortDescription: "AI pair programmer that suggests code completions, functions, and entire files in real-time across all major IDEs.",
      longDescription: "GitHub Copilot is an AI-powered code completion tool developed by GitHub and OpenAI. It integrates directly into VS Code, JetBrains IDEs, Neovim, and more, providing context-aware code suggestions as you type. With Copilot Chat, you can ask questions about your codebase, debug issues, and get explanations of complex code. It's trained on billions of lines of public code and can write entire functions, classes, and tests from natural language descriptions.",
      categoryId: catMap.get("code-development"),
      pricing: "paid",
      status: "approved",
      isVerified: true,
      isEditorChoice: true,
      views: 29500,
      clicks: 8900,
      bookmarkCount: 3400,
      ratingAvg: 4.6,
      reviewCount: 1450,
      trendingScore: 88.0,
      ownerName: "GitHub (Microsoft)",
      launchDate: "2021-06-29",
      aiModel: "GPT-4o",
      features: ["Code completion", "Function generation", "Test generation", "Copilot Chat", "CLI integration", "Multi-language support"],
      pros: ["Seamless IDE integration", "Understands codebase context", "Massive time saver", "Great test generation"],
      cons: ["$10-19/month", "Occasional incorrect suggestions", "Privacy concerns with code data"],
      platforms: ["VS Code", "JetBrains", "Neovim", "CLI"],
      integrations: ["GitHub", "VS Code", "JetBrains", "Azure"],
      tags: ["coding", "code completion", "developer tools", "AI programming", "IDE"],
    },
    {
      name: "DALL-E 3",
      slug: "dalle-3",
      websiteUrl: "https://openai.com/dall-e-3",
      shortDescription: "OpenAI's advanced image generation model with exceptional prompt understanding and photorealistic outputs.",
      longDescription: "DALL-E 3 is OpenAI's latest image generation model, integrated directly into ChatGPT. It excels at following complex, nuanced prompts with remarkable accuracy, understanding text, spatial relationships, and artistic styles better than any previous version. DALL-E 3 creates stunning, highly detailed images and is available via ChatGPT Plus and the OpenAI API.",
      categoryId: catMap.get("image-generation"),
      pricing: "freemium",
      status: "approved",
      isVerified: true,
      views: 21000,
      clicks: 6500,
      bookmarkCount: 1800,
      ratingAvg: 4.5,
      reviewCount: 890,
      trendingScore: 78.0,
      ownerName: "OpenAI",
      launchDate: "2023-10-03",
      aiModel: "DALL-E 3",
      features: ["High-resolution generation", "Text in images", "Style variety", "Prompt accuracy", "Safe content policies"],
      pros: ["Excellent prompt understanding", "Good text rendering", "API access", "Consistent quality"],
      cons: ["More conservative safety filters", "Not as artistic as Midjourney", "Limited customization"],
      platforms: ["Web", "API", "ChatGPT"],
      tags: ["image generation", "AI art", "OpenAI", "photorealistic"],
    },
    {
      name: "Jasper",
      slug: "jasper",
      websiteUrl: "https://jasper.ai",
      shortDescription: "Enterprise AI writing platform built for marketing teams, with brand voice, templates, and multi-channel content creation.",
      longDescription: "Jasper is an AI writing platform purpose-built for marketing and content teams. It goes beyond simple text generation with brand voice training, marketing-specific templates, multi-language support, and deep integrations with marketing tools. Teams use Jasper to create blog posts, social media content, email campaigns, ad copy, and product descriptions at scale while maintaining brand consistency.",
      categoryId: catMap.get("ai-writing"),
      pricing: "paid",
      status: "approved",
      isVerified: true,
      views: 15600,
      clicks: 4200,
      bookmarkCount: 980,
      ratingAvg: 4.3,
      reviewCount: 654,
      trendingScore: 65.0,
      ownerName: "Jasper AI",
      launchDate: "2021-01-01",
      features: ["Brand voice AI", "50+ templates", "Multi-language", "Team collaboration", "Chrome extension", "Plagiarism checker"],
      pros: ["Marketing-focused templates", "Brand voice consistency", "Team features", "Good integrations"],
      cons: ["Expensive", "Overkill for individuals", "Quality varies by template"],
      platforms: ["Web", "Chrome Extension", "API"],
      integrations: ["Surfer SEO", "Copyscape", "Zapier", "HubSpot"],
      tags: ["writing", "marketing", "copywriting", "content", "SEO"],
    },
    {
      name: "Notion AI",
      slug: "notion-ai",
      websiteUrl: "https://notion.so/ai",
      shortDescription: "AI built directly into Notion that helps you write, summarize, translate, and extract insights from your workspace.",
      longDescription: "Notion AI is deeply integrated into the Notion workspace, allowing you to use AI features without leaving your documents and databases. It can write, edit, summarize, translate, and fix grammar right where you work. The AI understands your workspace context, so it can answer questions about your documents, create action items from meeting notes, and help organize information intelligently.",
      categoryId: catMap.get("productivity"),
      pricing: "freemium",
      status: "approved",
      isVerified: true,
      views: 18400,
      clicks: 5200,
      bookmarkCount: 1540,
      ratingAvg: 4.4,
      reviewCount: 762,
      trendingScore: 72.0,
      ownerName: "Notion Labs",
      launchDate: "2023-02-22",
      features: ["Workspace-aware AI", "Auto-summarization", "Translation", "Q&A on documents", "Writing assistance", "Database queries"],
      pros: ["Deeply integrated into workflow", "Context-aware responses", "Easy to use", "Great for note-takers"],
      cons: ["Add-on cost", "Less powerful than dedicated tools", "Depends on Notion ecosystem"],
      platforms: ["Web", "Desktop", "iOS", "Android"],
      tags: ["productivity", "notes", "writing", "workspace", "documentation"],
    },
    {
      name: "Runway ML",
      slug: "runway-ml",
      websiteUrl: "https://runwayml.com",
      shortDescription: "AI-powered creative suite for video generation, editing, and visual effects used by leading studios and creators.",
      longDescription: "Runway is a pioneering AI creative platform that has brought generative AI to professional video production. Gen-2 and Gen-3 Alpha generate high-quality video from text and image prompts. Runway also offers AI-powered video editing tools including background removal, motion tracking, rotoscoping, and more. It's used by filmmakers, advertisers, and content creators who need cutting-edge AI video capabilities.",
      categoryId: catMap.get("video-animation"),
      pricing: "freemium",
      status: "featured",
      isVerified: true,
      isEditorChoice: true,
      views: 24300,
      clicks: 7100,
      bookmarkCount: 2200,
      ratingAvg: 4.5,
      reviewCount: 934,
      trendingScore: 89.0,
      ownerName: "Runway AI",
      launchDate: "2018-01-01",
      aiModel: "Gen-3 Alpha",
      features: ["Text-to-video", "Image-to-video", "Video editing", "Background removal", "Motion tracking", "Inpainting", "Multi-modal generation"],
      pros: ["Professional quality output", "Comprehensive editing suite", "Regular model updates", "Great for filmmakers"],
      cons: ["Expensive for heavy use", "Processing time can be slow", "Learning curve"],
      platforms: ["Web", "API"],
      tags: ["video generation", "video editing", "creative", "filmmaking", "generative AI"],
    },
    {
      name: "ElevenLabs",
      slug: "elevenlabs",
      websiteUrl: "https://elevenlabs.io",
      shortDescription: "Industry-leading AI voice synthesis with ultra-realistic text-to-speech, voice cloning, and multilingual support.",
      longDescription: "ElevenLabs is the gold standard in AI voice synthesis. Its text-to-speech technology produces remarkably natural, emotionally expressive speech in 29 languages. Voice cloning technology can recreate any voice from just a few minutes of audio. Used by publishers, podcasters, game developers, and content creators worldwide, ElevenLabs offers voices that are nearly indistinguishable from human speech.",
      categoryId: catMap.get("audio-music"),
      pricing: "freemium",
      status: "approved",
      isVerified: true,
      isEditorChoice: true,
      views: 22100,
      clicks: 6800,
      bookmarkCount: 1900,
      ratingAvg: 4.7,
      reviewCount: 1120,
      trendingScore: 84.0,
      ownerName: "ElevenLabs",
      launchDate: "2022-01-06",
      features: ["Ultra-realistic TTS", "Voice cloning", "29 languages", "Voice library", "Dubbing", "Sound effects", "Projects feature"],
      pros: ["Most realistic AI voices", "Excellent emotional expression", "Large voice library", "Great API"],
      cons: ["Free tier limited", "Voice cloning can be misused", "Costs add up with usage"],
      platforms: ["Web", "API", "iOS"],
      integrations: ["Zapier", "Make", "Various podcasting tools"],
      tags: ["voice synthesis", "text-to-speech", "voice cloning", "audio", "podcasting"],
    },
    {
      name: "Perplexity AI",
      slug: "perplexity-ai",
      websiteUrl: "https://perplexity.ai",
      shortDescription: "AI-powered search engine that provides accurate, cited answers to complex questions with real-time web access.",
      longDescription: "Perplexity AI is reimagining search with AI. Unlike traditional search engines that return a list of links, Perplexity synthesizes information from across the web to provide comprehensive, cited answers. It's particularly useful for research, fact-checking, and getting quick answers to complex questions. The Pro version offers access to GPT-4, Claude, and other frontier models alongside real-time search.",
      categoryId: catMap.get("research-analysis"),
      pricing: "freemium",
      status: "featured",
      isVerified: true,
      isEditorChoice: false,
      views: 28900,
      clicks: 8700,
      bookmarkCount: 2800,
      ratingAvg: 4.6,
      reviewCount: 1340,
      trendingScore: 92.0,
      ownerName: "Perplexity AI",
      launchDate: "2022-12-07",
      features: ["Real-time web search", "Citation-backed answers", "Multi-model support", "Focus modes", "Collections", "API access"],
      pros: ["Always up-to-date information", "Cites sources", "Fast and accurate", "Multiple AI models"],
      cons: ["Pro version required for best models", "Sometimes over-summarizes", "Sources can vary in quality"],
      platforms: ["Web", "iOS", "Android", "API"],
      tags: ["search", "research", "AI search", "real-time", "citations"],
    },
    {
      name: "Stable Diffusion",
      slug: "stable-diffusion",
      websiteUrl: "https://stability.ai",
      shortDescription: "The leading open-source image generation model you can run locally or in the cloud with complete control.",
      longDescription: "Stable Diffusion is a revolutionary open-source image generation model developed by Stability AI. Unlike cloud-only tools, it can be run locally on consumer hardware, giving users complete control over their image generation without usage limits or censorship. With thousands of community models, LoRAs, and extensions available via Automatic1111 and ComfyUI, the customization possibilities are essentially limitless.",
      categoryId: catMap.get("image-generation"),
      pricing: "free",
      status: "approved",
      isVerified: true,
      views: 19800,
      clicks: 5900,
      bookmarkCount: 2700,
      ratingAvg: 4.5,
      reviewCount: 1567,
      trendingScore: 76.0,
      ownerName: "Stability AI",
      githubUrl: "https://github.com/CompVis/stable-diffusion",
      launchDate: "2022-08-22",
      features: ["Open source", "Local execution", "Thousands of community models", "ControlNet", "Inpainting", "img2img", "Infinite customization"],
      pros: ["Completely free", "No usage limits locally", "Massive community", "Full control"],
      cons: ["Requires technical setup", "GPU needed for best performance", "Quality varies by model"],
      platforms: ["Windows", "Mac", "Linux", "Cloud"],
      tags: ["image generation", "open source", "local AI", "stable diffusion", "free"],
    },
    {
      name: "Grammarly",
      slug: "grammarly",
      websiteUrl: "https://grammarly.com",
      shortDescription: "AI writing assistant that improves grammar, style, tone, and clarity across all your writing platforms.",
      longDescription: "Grammarly is the world's most popular AI writing assistant, used by over 30 million people daily. It goes far beyond spell-checking to suggest improvements to tone, style, clarity, and engagement. GrammarlyGO brings generative AI capabilities to help brainstorm ideas, rewrite paragraphs, and draft content. It works seamlessly across browsers, desktop apps, Microsoft Office, and mobile.",
      categoryId: catMap.get("ai-writing"),
      pricing: "freemium",
      status: "approved",
      isVerified: true,
      views: 16700,
      clicks: 4800,
      bookmarkCount: 1200,
      ratingAvg: 4.3,
      reviewCount: 892,
      trendingScore: 68.0,
      ownerName: "Grammarly Inc.",
      launchDate: "2009-07-01",
      features: ["Grammar & spell check", "Tone detection", "Style suggestions", "Plagiarism checker", "GrammarlyGO", "Chrome extension"],
      pros: ["Works everywhere", "Easy to use", "Catches subtle errors", "Good free tier"],
      cons: ["Premium required for advanced features", "Can be overly prescriptive", "Not ideal for technical writing"],
      platforms: ["Web", "Chrome", "Desktop", "iOS", "Android", "Microsoft Office"],
      tags: ["writing", "grammar", "proofreading", "editing", "productivity"],
    },
  ]).returning().onConflictDoNothing();

  console.log(`Inserted ${tools.length} tools`);

  // Blog Posts
  const blogPosts = await db.insert(blogPostsTable).values([
    {
      title: "The 10 Best AI Writing Tools in 2025: A Comprehensive Guide",
      slug: "best-ai-writing-tools-2025",
      excerpt: "From ChatGPT to Jasper, we've tested dozens of AI writing tools to find the ones that actually improve your writing workflow.",
      content: "# The 10 Best AI Writing Tools in 2025\n\nAI writing tools have matured significantly in 2025. What started as simple text autocomplete has evolved into sophisticated systems that can write entire articles, match brand voice, and adapt to any writing style...\n\n## 1. ChatGPT — Best All-Around AI Writer\n\nChatGPT remains the most versatile writing tool available. Whether you need a quick email, a detailed blog post, or a creative short story, GPT-4 delivers...",
      authorName: "Sarah Chen",
      authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
      category: "Guides",
      tags: ["AI writing", "tools", "guide", "2025"],
      readingTime: 12,
      coverImage: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1200&q=80",
      status: "published",
      publishedAt: new Date("2025-06-15"),
    },
    {
      title: "How to Use AI Image Generation for Your Business",
      slug: "ai-image-generation-business-guide",
      excerpt: "Practical guide to integrating AI image tools like Midjourney, DALL-E 3, and Stable Diffusion into your business workflows.",
      content: "# How to Use AI Image Generation for Your Business\n\nAI image generation has gone from novelty to necessity for businesses in 2025. Marketing teams, product designers, and content creators are using tools like Midjourney and DALL-E 3 to cut creative costs by 60% or more...",
      authorName: "Marcus Rivera",
      authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus",
      category: "Business",
      tags: ["image generation", "business", "marketing", "workflow"],
      readingTime: 9,
      coverImage: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1200&q=80",
      status: "published",
      publishedAt: new Date("2025-06-22"),
    },
    {
      title: "AI Coding Assistants Compared: GitHub Copilot vs Cursor vs Codeium",
      slug: "ai-coding-assistants-compared",
      excerpt: "We spent 3 months using the top AI coding tools on real projects. Here's everything you need to know.",
      content: "# AI Coding Assistants Compared\n\nThe AI coding assistant landscape has exploded in the past year. GitHub Copilot pioneered the category, but now Cursor, Codeium, Tabnine, and a dozen other tools are competing for developer attention...",
      authorName: "Alex Kim",
      authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
      category: "Development",
      tags: ["coding", "developer tools", "comparison", "productivity"],
      readingTime: 15,
      coverImage: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=1200&q=80",
      status: "published",
      publishedAt: new Date("2025-07-01"),
    },
    {
      title: "The Complete Guide to AI Prompt Engineering",
      slug: "complete-guide-ai-prompt-engineering",
      excerpt: "Master the art of writing prompts that get exactly what you want from ChatGPT, Claude, Midjourney, and other AI tools.",
      content: "# The Complete Guide to AI Prompt Engineering\n\nPrompt engineering has emerged as one of the most valuable skills in the AI era. The difference between a mediocre AI output and an exceptional one often comes down to how you frame your request...",
      authorName: "Sarah Chen",
      authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
      category: "Guides",
      tags: ["prompt engineering", "AI tips", "ChatGPT", "Claude"],
      readingTime: 18,
      coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&q=80",
      status: "published",
      publishedAt: new Date("2025-07-08"),
    },
  ]).returning().onConflictDoNothing();

  console.log(`Inserted ${blogPosts.length} blog posts`);

  // News
  const news = await db.insert(newsTable).values([
    {
      title: "OpenAI Releases GPT-5 with Unprecedented Reasoning Capabilities",
      slug: "openai-gpt5-reasoning-capabilities",
      excerpt: "OpenAI's latest model demonstrates PhD-level reasoning in science, mathematics, and law, setting a new benchmark for frontier AI.",
      content: "OpenAI has unveiled GPT-5, its most capable model to date, with dramatic improvements in reasoning, scientific understanding, and multi-step problem solving...",
      sourceUrl: "https://openai.com/research/gpt-5",
      category: "Product Launch",
      isTrending: true,
      publishedAt: new Date("2025-07-10"),
    },
    {
      title: "Google DeepMind's Gemini Ultra 2.0 Tops All AI Benchmarks",
      slug: "google-deepmind-gemini-ultra-2-benchmarks",
      excerpt: "Gemini Ultra 2.0 achieves state-of-the-art performance across all major AI benchmarks, challenging OpenAI's dominance.",
      content: "Google DeepMind has released Gemini Ultra 2.0, a multimodal AI model that outperforms all previous models on a comprehensive set of benchmarks...",
      sourceUrl: "https://deepmind.google/research/gemini",
      category: "Research",
      isTrending: true,
      publishedAt: new Date("2025-07-08"),
    },
    {
      title: "Anthropic Raises $2.5B to Accelerate Claude Development",
      slug: "anthropic-raises-2-5-billion-funding",
      excerpt: "The AI safety company secures massive funding round as demand for Claude API skyrockets among enterprise customers.",
      content: "Anthropic has closed a $2.5 billion funding round led by Google and a consortium of venture capital firms, bringing its total valuation to over $20 billion...",
      sourceUrl: "https://anthropic.com",
      category: "Funding",
      isTrending: false,
      publishedAt: new Date("2025-07-05"),
    },
    {
      title: "EU AI Act Takes Effect: What It Means for AI Tool Developers",
      slug: "eu-ai-act-takes-effect-developers",
      excerpt: "The European Union's landmark AI regulation is now in force. Here's what AI tool developers and companies need to know.",
      content: "The EU AI Act has officially taken effect, marking a watershed moment in AI regulation. The legislation categorizes AI systems by risk level and imposes corresponding requirements...",
      sourceUrl: "https://artificialintelligenceact.eu",
      category: "Regulation",
      isTrending: true,
      publishedAt: new Date("2025-07-03"),
    },
    {
      title: "Stability AI Releases SDXL Turbo: Real-Time Image Generation",
      slug: "stability-ai-sdxl-turbo-real-time",
      excerpt: "New distillation technique enables near-instant image generation on consumer hardware, democratizing AI art creation.",
      content: "Stability AI has released SDXL Turbo, a new model architecture that enables real-time image generation using adversarial diffusion distillation...",
      sourceUrl: "https://stability.ai",
      category: "Research",
      isTrending: false,
      publishedAt: new Date("2025-06-28"),
    },
  ]).returning().onConflictDoNothing();

  console.log(`Inserted ${news.length} news articles`);

  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
